#Gradle
org.gradle.jvmargs=-Xmx3G -Djava.net.preferIPv4Stack=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.parallel=true

#Kotlin
kotlin.daemon.jvmargs=-Xmx3G -Djava.net.preferIPv4Stack=true
kotlin.native.binary.gc=cms

#Android
android.useAndroidX=true

BASE_URL=https://staging.aispeaking.ir/

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

# Gradle Network Timeouts (3 minutes)
systemProp.org.gradle.internal.http.connectionTimeout=180000
systemProp.org.gradle.internal.http.socketTimeout=180000
