#Gradle
org.gradle.jvmargs=-Xmx4G
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.daemon=true
org.gradle.parallel=true

#Kotlin
kotlin.daemon.jvmargs=-Xmx4G
kotlin.native.binary.gc=cms

#Android
android.useAndroidX=true

BASE_URL=https://staging.aispeaking.ir/


# System proxy configuration for Gradle
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=10808
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=10808
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
